server:
  port: 8013


#http请求地址和资源文件映射如下:
#    /{application}/{profile}[/{label}] 默认
#    /{application}-{profile}.yml
#    /{label}/{application}-{profile}.yml
#    /{application}-{profile}.properties
#    /{label}/{application}-{profile}.properties

#http://localhost:8014/application-a13.properties   会利用git机制，先更新到本地，在使用时，每次使用先更新，再使用。
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zk20180228/springcloud-config-server # github的仓库地址
          search-paths: resources # 仓库下哪一个目录  如/**-->所有
          # basedir: 本地仓库地址，默认在---->看打印得到日志
          #username:  # 用户名密码，如果是公共的github仓库，可以不用username和password
          #password:
        #svn:
          #uri: svn配置，和git很像
      label: master   # 哪一个分支

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

#config-server可以不用加，但是在不知道刷新配置的路径时，可以添加此依赖，暴露所有
#监控接口，来找到手动刷新配置的接口
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"