server:
  port: 8002
  servlet:
    context-path: /
spring:
  application:
    name: springcloud-client-a #相同的applicationName为同一个集群，访问时，通过该名访问

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true #配置在eureka的主页面显示ip，但是访问还是通过applicationName,仅作展示使用
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #配置在eureka的主页面显示的应用的instance-id
    #home-page-url-path:/  #当前应用的server.servlet.context-path，默认是/
# renewal-->续约  interval-->间隔 --->客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
#eureka.client.healthcheck.enabled	# 开启健康检查（需要spring-boot-starter-actuator依赖）
#eureka.instance.lease-renewal-interval-in-seconds	# 续约更新时间间隔（默认30秒）
#expiration-->截至 duration-->持续--->服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
#eureka.instance.lease-expiration-duration-in-seconds # 续约到期时间（默认90秒）

