server:
  port: 8004

spring:
  application:
    name: springcloud-consumer-eureka-a

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true #配置在eureka的主页面显示ip，但是访问还是通过applicationName,仅作展示使用
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #配置在eureka的主页面显示的应用的instance-id