server:
  port: 8005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30

spring:
  application:
    name: springcloud-consumer-feign-a
