server:
  port: 8006

spring:
  application:
    name: springcloud-eureka-hystrix-a

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90