server:
  port: 8015
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zk20180228/springcloud-config-server # github的仓库地址
          search-paths: resources # 仓库下哪一个目录  如/**-->所有
      label:  master
  application:
    name: springcloud-config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30

#config-server可以不用加，但是在不知道刷新配置的路径时，可以添加此依赖，暴露所有
#监控接口，来找到手动刷新配置的接口
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

