server:
  port: 8012
spring:
  application:
    name: springcloud-eureka-order-a12
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90


